apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::314793935059:role/external_secrets_role
  labels:
    name: kubernetes-external-secrets
