apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::238129518993:role/external_secrets_role
  labels:
    name: kubernetes-external-secrets
