apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/argocd/https_username-800e640d
    name: HTTPS_USERNAME
  - key: kubeflow/argocd/https_password-800e640d
    name: HTTPS_PASSWORD
