kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
data:
  DB_NAME_PIPELINES: mlpipeline
  DB_NAME_CACHE: cachedb
  DB_NAME_METADATA: metadb
  RDS_HOST: terraform-20220127033346945700000005.cgc2dcgarklj.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
