kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
data:
  REGION: ap-southeast-1
  BUCKET_NAME: kubeflow-pipelines-8779d42f
  PIPELINE_FOLDER: pipelines
  PIPELINE_PATH: pipelines
