apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/kubeflow/s3_accesskey-12022b2a
    name: S3_ACCESSKEY
  - key: kubeflow/kubeflow/s3_secretkey-12022b2a
    name: S3_SECRETKEY
