apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::106256755710:role/external_secrets_kubeflow_role
  data:
  - key: kubeflow/kubeflow/s3_accesskey-ec567a79
    name: S3_ACCESSKEY
  - key: kubeflow/kubeflow/s3_secretkey-ec567a79
    name: S3_SECRETKEY
