apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::106256755710:role/external_secrets_role
  data:
  - key: kubeflow/auth/client_id-ec567a79
    name: client-id
  - key: kubeflow/auth/client_secret-ec567a79
    name: client-secret
  - key: kubeflow/auth/cookie_secret-ec567a79
    name: cookie-secret
