apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/auth/client_id-7d76d41c
    name: client-id
  - key: kubeflow/auth/client_id-7d76d41c
    name: client-secret
  - key: kubeflow/auth/cookie_secret-7d76d41c
    name: cookie-secret
