apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
  - key: kubeflow/istio-system/auth_ca_cert-ff6e196c
    name: ca.crt
  - key: kubeflow/istio-system/auth_cert-ff6e196c
    name: tls.crt
  - key: kubeflow/istio-system/auth_cert_pk-ff6e196c
    name: tls.key
