apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: <<__external_secrets.backend_type__>>
  template:
    type: kubernetes.io/tls
  data:
  - key: <<__external_secret_name.istio_system.auth_ca_cert__>>
    name: ca.crt
  - key: <<__external_secret_name.istio_system.auth_cert__>>
    name: tls.crt
  - key: <<__external_secret_name.istio_system.auth_cert_pk__>>
    name: tls.key
