apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
  - key: kubeflow/istio-system/gateway_ca_cert-800e640d-lXSNjg
    name: ca.crt
  - key: kubeflow/istio-system/gateway_cert-800e640d-4itUh5
    name: tls.crt
  - key: kubeflow/istio-system/gateway_cert_pk-800e640d-O70qUm
    name: tls.key
