apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
  - key: kubeflow/istio-system/gateway_ca_cert-71f1014d
    name: ca.crt
  - key: kubeflow/istio-system/gateway_cert-71f1014d
    name: tls.crt
  - key: kubeflow/istio-system/gateway_cert_pk-71f1014d
    name: tls.key
