apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
  - key: kubeflow/istio-system/monitoring_ca_cert-b9a59c2f
    name: ca.crt
  - key: kubeflow/istio-system/monitoring_cert-b9a59c2f
    name: tls.crt
  - key: kubeflow/istio-system/monitoring_cert_pk-b9a59c2f
    name: tls.key
