apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
  - key: kubeflow/istio-system/monitoring_ca_cert-800e640d-lXSNjg
    name: ca.crt
  - key: kubeflow/istio-system/monitoring_cert-800e640d-kkI166
    name: tls.crt
  - key: kubeflow/istio-system/monitoring_cert_pk-800e640d-IL0sAb
    name: tls.key
