apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:
  selfSigned:
    $patch: delete
  acme:
    email: honest.engineering@honestbank.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z0368304OGCUI6XQT54A
          region: ap-southeast-1
          # role: arn:aws:iam::238129518993:role/cert_manager_role
