apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honestbank/argoflow-aws.git
    targetRevision: test-0.1.6-branch
    path: distribution/certificates/overlays/imported
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
