apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honestbank/argoflow-aws.git
    targetRevision: refs/heads/test
    path: distribution/kubeflow/notebooks/jupyter-web-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
