apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honestbank/argoflow-aws.git
    targetRevision: refs/heads/qa
    path: distribution/kubeflow/kfserving
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
