apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honestbank/argoflow-aws.git
    targetRevision: refs/heads/test
    path: distribution/oidc-auth/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
