apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xgboost-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honestbank/argoflow-aws.git
    targetRevision: refs/tags/test
    path: distribution/kubeflow/operators/xgboost
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
