apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
  - grafana.kfprod.honestbank.com
  - kiali.kfprod.honestbank.com
  - kubecost.kfprod.honestbank.com
