kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-20220127033346945700000005.cgc2dcgarklj.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-cff8a512
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
