kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-20210919084742972400000001.cja7ju74p6du.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-3ea4736d
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
