kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-20211205083629812400000009.cz99vii6ez38.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-e1e4ebe3
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
