kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: "terraform-20210912035910656200000001.ceayezvmaz7m.ap-southeast-1.rds.amazonaws.com"
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: argoflow-aws-mlflow-poc-1
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
