kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-2021112109160929030000000a.crvvghbyahd5.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-5acded05
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
