kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-2022022507490594510000000a.cja7ju74p6du.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-d28bd32c
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
