kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: terraform-20220228035521627500000008.crvvghbyahd5.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: kubeflow-mlflow-fa343149
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
