apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: mlflow
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/mlflow/rds_username-71f1014d
    name: RDS_USERNAME
  - key: kubeflow/mlflow/rds_password-71f1014d
    name: RDS_PASSWORD
