apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: mlflow
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/mlflow/rds_username-b9a59c2f
    name: RDS_USERNAME
  - key: kubeflow/mlflow/rds_password-b9a59c2f
    name: RDS_PASSWORD
