kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: katib
  RDS_HOST: terraform-2022022507490594510000000a.cja7ju74p6du.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
