kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: katib
  RDS_HOST: terraform-20211205083629812400000009.cz99vii6ez38.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
