apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: katib-rds-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/kubeflow/rds_username-800e640d-IazC2n
    name: RDS_USERNAME
  - key: kubeflow/kubeflow/rds_password-800e640d-XXgpzW
    name: RDS_PASSWORD
