apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: katib-rds-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  data:
  - key: kubeflow/kubeflow/rds_username-ff6e196c
    name: RDS_USERNAME
  - key: kubeflow/kubeflow/rds_password-ff6e196c
    name: RDS_PASSWORD
