kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: katib
  RDS_HOST: terraform-2021112109160929030000000a.crvvghbyahd5.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
