apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: katib-rds-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::106256755710:role/external_secrets_kubeflow_role
  data:
  - key: kubeflow/kubeflow/rds_username-ec567a79
    name: RDS_USERNAME
  - key: kubeflow/kubeflow/rds_password-ec567a79
    name: RDS_PASSWORD
