kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: katib
  RDS_HOST: terraform-20220127033346945700000005.cgc2dcgarklj.ap-southeast-1.rds.amazonaws.com
  RDS_PORT: "3306"
