apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: profile-controller
        command: [python, /hooks/sync_with_s3.py]
        env:
        - name: SECRET_NAME_S3_ACCESSKEY
          value: kubeflow/kubeflow/s3_accesskey-351586e0
        - name: SECRET_NAME_S3_SECRETKEY
          value: kubeflow/kubeflow/s3_secretkey-351586e0
        - name: EXTERNAL_SECRET_ROLE_ARN
          value: arn:aws:iam::226528313721:role/external_secrets_role
        - name: EXTERNAL_SECRET_BACKEND_TYPE
          value: secretsManager

        # remove minio-related params
        - $patch: delete
          name: MINIO_ACCESS_KEY
        - $patch: delete
          name: MINIO_SECRET_KEY
