apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc-deployment
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: container
        image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0@sha256:e4657696d1aa0a1ea94c5830abb166d6abf4b0cf45859ab8a68aae352a2825f2
        env:
        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              name: pipelines-rds-secret
              key: RDS_USERNAME
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pipelines-rds-secret
              key: RDS_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pipelines-rds-config
              key: DB_NAME_METADATA
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: pipelines-rds-config
              key: RDS_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: pipelines-rds-config
              key: RDS_PORT
