apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: kubeflow-pipelines-09bc341d
      keyPrefix: pipelines/artifacts
      endpoint: s3.amazonaws.com
      region: ap-southeast-1
      insecure: false
      accessKeySecret:
        name: pipelines-s3-secret
        key: S3_ACCESSKEY
      secretKeySecret:
        name: pipelines-s3-secret
        key: S3_SECRETKEY
  containerRuntimeExecutor: pns
  # namespace: kubeflow
  # executorImage: gcr.io/ml-pipeline/argoexec:v2.7.5-license-compliance
