apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
data:
  gateway.kubeflow.kfserving-gateway: istio-kfserving-ingressgateway.istio-system.svc.cluster.local
  local-gateway.istio-system.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
  enable-virtualservice-status: 'true'
  # local-gateway.mesh: mesh
