apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-viewer-template
data:
  viewer-tensorboard-template.json: |
    {
        "metadata": {
            "annotations": {
                "iam.amazonaws.com/role": "arn:aws:iam::890123456789:role/kubeflow_kubeflow_kube2iam_pipelines"
            }
        },
        "spec": {
            "containers": [
                {
                    "env": [
                        {
                            "name": "AWS_REGION",
                            "value": "ap-southeast-1"
                        }
                    ]
                }
            ]
        }
    }
