apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  backendType: <<__external_secrets.backend_type__>>
  data:
  - key: <<__external_secret_name.monitoring.grafana_username__>>
    name: admin-user
  - key: <<__external_secret_name.monitoring.grafana_password__>>
    name: admin-password
